#version: '3.8'

services:
  php81-cli:
    image: php:8.1-apache
    container_name: php81_cli
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - kafka
      - rabbitmq
      - elasticsearch

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9094:9094"
    networks:
      - app-network
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network





  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      # rabbitmq_management：管理界面
      # rabbitmq_delayed_message_exchange：延迟消息交换
      # rabbitmq_consistent_hash_exchange：一致性哈希交换
      # rabbitmq_top：用于查看 RabbitMQ 状态
      RABBITMQ_PLUGINS: rabbitmq_delayed_message_exchange rabbitmq_consistent_hash_exchange rabbitmq_top
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mq-network

  rabbitmq2:
    image: rabbitmq:3-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      #RABBITMQ_PLUGINS: rabbitmq_delayed_message_exchange rabbitmq_consistent_hash_exchange rabbitmq_top
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
#    command:
#      - bash
#      - -c
#      - |
#        rabbitmq-server -detached && rabbitmqctl stop_app && rabbitmqctl join_cluster rabbit@rabbitmq && rabbitmqctl start_app
#    networks:
#      - mq-network

  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      #RABBITMQ_PLUGINS: rabbitmq_delayed_message_exchange rabbitmq_consistent_hash_exchange rabbitmq_top
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      - mq-network







  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node  # 设置为单节点
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # JVM 内存设置
      - "http.host=0.0.0.0"  # 允许外部访问
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data  # 数据持久化
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app-network




networks:
  mq-network:
  app-network:
    driver: bridge

volumes:
  esdata:
    driver: local
  rabbitmq_data:
#  rabbitmq2_data:
#  rabbitmq3_data:
